### PR TITLE
feat: 混淆压缩APP体积，跳过自身混淆精简。

### PR DESCRIPTION
**Pull request by mymine**

### CODE REVIEW

**Comment by XayahSuSuSu** [comment]
```
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  java.lang.NullPointerException: Parameter specified as non-null is null: method s7.i.F0, parameter <this>
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at s7.i.F0(Unknown Source:2)
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.ui.activity.guide.components.UpdateKt$Update$2$1$1.l0(Unknown Source:104)
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.util.Server$releases$2.j(Unknown Source:106)
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at d7.a.t(Unknown Source:8)
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at t7.h0.run(Unknown Source:100)
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
```
混淆关了就是Kotlin缩减后的Bug，会导致无法获取更新

**Comment by mymine** [comment]
proguard-rules.pro
添加
-dontwarn com.xayah.databackup.**
-keep class com.xayah.databackup.** { *; }

**Comment by mymine** [comment]
> ```
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  java.lang.NullPointerException: Parameter specified as non-null is null: method s7.i.F0, parameter <this>
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at s7.i.F0(Unknown Source:2)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.ui.activity.guide.components.UpdateKt$Update$2$1$1.l0(Unknown Source:104)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.util.Server$releases$2.j(Unknown Source:106)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at d7.a.t(Unknown Source:8)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at t7.h0.run(Unknown Source:100)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
> ```
> 
> 混淆关了就是Kotlin缩减后的Bug，会导致无法获取更新

刚编译出来的，你测试下https://we.tl/t-Sqjhmx6BL4

**Comment by mymine** [comment]
> ```
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  java.lang.NullPointerException: Parameter specified as non-null is null: method s7.i.F0, parameter <this>
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at s7.i.F0(Unknown Source:2)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.ui.activity.guide.components.UpdateKt$Update$2$1$1.l0(Unknown Source:104)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.util.Server$releases$2.j(Unknown Source:106)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at d7.a.t(Unknown Source:8)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at t7.h0.run(Unknown Source:100)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
> 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
> ```
> 
> 混淆关了就是Kotlin缩减后的Bug，会导致无法获取更新

这是编译的4.1.6fix版。云端，云备份正常使用。
https://wetransfer.com/downloads/5e81c2bd44d0945d7b4700b3c8fee67020230224133022/a7f7d7

**Comment by XayahSuSuSu** [comment]
> > ```
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  java.lang.NullPointerException: Parameter specified as non-null is null: method s7.i.F0, parameter <this>
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at s7.i.F0(Unknown Source:2)
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.ui.activity.guide.components.UpdateKt$Update$2$1$1.l0(Unknown Source:104)
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.util.Server$releases$2.j(Unknown Source:106)
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at d7.a.t(Unknown Source:8)
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at t7.h0.run(Unknown Source:100)
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
> > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 混淆关了就是Kotlin缩减后的Bug，会导致无法获取更新
> 
> 这是编译的4.1.6fix版。云端，云备份正常使用。 https://wetransfer.com/downloads/5e81c2bd44d0945d7b4700b3c8fee67020230224133022/a7f7d7

需要关闭混淆，另外提交太脏了，我需要force push一下

**Comment by mymine** [comment]
> > > ```
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  java.lang.NullPointerException: Parameter specified as non-null is null: method s7.i.F0, parameter <this>
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at s7.i.F0(Unknown Source:2)
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.ui.activity.guide.components.UpdateKt$Update$2$1$1.l0(Unknown Source:104)
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at com.xayah.databackup.util.Server$releases$2.j(Unknown Source:106)
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at d7.a.t(Unknown Source:8)
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at t7.h0.run(Unknown Source:100)
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
> > > 2023-02-27 19:05:57.055 25405-25532 System.err              com.xayah.databackup                 W  	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 混淆关了就是Kotlin缩减后的Bug，会导致无法获取更新
> > 
> > 
> > 这是编译的4.1.6fix版。云端，云备份正常使用。 https://wetransfer.com/downloads/5e81c2bd44d0945d7b4700b3c8fee67020230224133022/a7f7d7
> 
> 需要关闭混淆，另外提交太脏了，我需要force push一下

release发布版开启，ebug测试版关闭吧。

**Comment by XayahSuSuSu** [comment]
[R27](https://github.com/XayahSuSuSu/Android-DataBackup/pull/93/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R27)
这一行的意义是啥，可以去掉吗

**Comment by mymine** [comment]
> [R27](https://github.com/XayahSuSuSu/Android-DataBackup/pull/93/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R27) 这一行的意义是啥，可以去掉吗

可以，这个debug测试用的，

**Comment by XayahSuSuSu** [comment]
> > [R27](https://github.com/XayahSuSuSu/Android-DataBackup/pull/93/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R27) 这一行的意义是啥，可以去掉吗
> 
> 可以，这个debug测试用的，

https://stackoverflow.com/a/27945893
根据这个来看，`debuggable`和`zipAlignEnabled`均可移除

**Comment by mymine** [comment]
> > > [R27](https://github.com/XayahSuSuSu/Android-DataBackup/pull/93/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R27) 这一行的意义是啥，可以去掉吗
> > 
> > 
> > 可以，这个debug测试用的，
> 
> https://stackoverflow.com/a/27945893 根据这个来看，`debuggable`和`zipAlignEnabled`均可移除

是的

**Comment by XayahSuSuSu** [comment]
感谢

**Pull request merged**
